const USER_LOGOUT = "USER_LOGOUT";

// LOGIN
const LOGIN_SUBMIT_SUCCESS = "LOGIN_SUBMIT_SUCCESS";
const LOGIN_SUBMIT_FAILURE = "LOGIN_SUBMIT_FAILURE";
const LOGIN_CLEAR_ERRORS = "LOGIN_CLEAR_ERRORS";

// REGISTRATION
const REGISTRATION_SUBMIT_SUCCESS = "REGISTRATION_SUBMIT_SUCCESS";
const REGISTRATION_SUBMIT_FAILURE = "REGISTRATION_SUBMIT_FAILURE";
const REGISTRATION_CLEAR_ERRORS = "REGISTRATION_CLEAR_ERRORS";

export {
  USER_LOGOUT,
  LOGIN_SUBMIT_SUCCESS,
  LOGIN_SUBMIT_FAILURE,
  LOGIN_CLEAR_ERRORS,
  REGISTRATION_SUBMIT_SUCCESS,
  REGISTRATION_SUBMIT_FAILURE,
  REGISTRATION_CLEAR_ERRORS
};
