const SUBMITTED_LOGIN_FORM = 'SUBMITTED_LOGIN_FORM';
const SUBMITTED_REGISTRATION_FORM = 'SUBMITTED_REGISTRATION_FORM';
const UPDATE_NAME = 'UPDATE_NAME';
const CLEAR_ERRORS = 'CLEAR_ERRORS';


export {
  SUBMITTED_LOGIN_FORM,
  SUBMITTED_REGISTRATION_FORM,
  UPDATE_NAME,
  CLEAR_ERRORS
}