
// LOGIN
const LOGIN_SUBMIT_SUCCESS = "LOGIN_SUBMIT_SUCCESS";
const LOGIN_SUBMIT_FAILURE = "LOGIN_SUBMIT_FAILURE";
const LOGIN_SET_ERRORS = "LOGIN_SET_ERRORS";

// REGISTRATION
const REGISTRATION_SUBMIT_SUCCESS = "REGISTRATION_SUBMIT_SUCCESS";
const REGISTRATION_SUBMIT_FAILURE = "REGISTRATION_SUBMIT_FAILURE";
const REGISTRATION_SET_ERRORS = "REGISTRATION_SET_ERRORS";

// USERS
const USER_LOGOUT = "USER_LOGOUT";
const USER_ADD_NEW = "USER_ADD_NEW";
const USER_CHECK_USERNAME = "USER_CHECK_USERNAME";

export {
  USER_LOGOUT,
  USER_ADD_NEW,
  USER_CHECK_USERNAME,
  LOGIN_SUBMIT_SUCCESS,
  LOGIN_SUBMIT_FAILURE,
  LOGIN_SET_ERRORS,
  REGISTRATION_SUBMIT_SUCCESS,
  REGISTRATION_SUBMIT_FAILURE,
  REGISTRATION_SET_ERRORS
};
